name: "Hello action"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME: 
    description: "Who to greet"
    required: true
    default: "Someone"
  YOUR_NAME: 
    description: "Who to greet"
    required: true
    default: "Brian"
    
runs:
  using: "docker"
  image: "Dockerfile"
  
branding:
  icon: "mic"
  color: "purple"
